In [1]:
import tensorflow as tf
print(tf.__version__)

2024-03-07 20:05:48.942949: I external/local_tsl/tsl/cuda/cudart_stub.cc:31] Could not find cuda drivers on your machine, GPU will not be used.
2024-03-07 20:05:48.978285: E external/local_xla/xla/stream_executor/cuda/cuda_dnn.cc:9261] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
2024-03-07 20:05:48.978312: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:607] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
2024-03-07 20:05:48.979028: E external/local_xla/xla/stream_executor/cuda/cuda_blas.cc:1515] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
2024-03-07 20:05:48.984199: I external/local_tsl/tsl/cuda/cudart_stub.cc:31] Could not find cuda drivers on your machine, GPU will not be used.
2024-03-07 20:05:48.985113: I tensorflow/core/platform/cpu_feature_guard.cc:1

2.15.0


## Create tensors with tf.constant()

In [2]:
scalar = tf.constant(7)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [3]:
# Check the number of dimensions of a tensor 
scalar.ndim

0

In [4]:
# Create a vector
vector = tf.constant([10, 10])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10], dtype=int32)>

In [5]:
# Check a dimension of our vector
vector.ndim

1

In [6]:
# Create a matrix (has more than one dimensions)
matrix = tf.constant([[10, 7], 
                      [7, 10]])
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 7, 10]], dtype=int32)>

In [7]:
matrix.ndim

2

In [8]:
# Create another matrix
another_matrix = tf.constant([[10., 7.],
                              [3., 2.],
                              [8., 9.]], dtype=tf.float16) # Specify dtype parameter
another_matrix

<tf.Tensor: shape=(3, 2), dtype=float16, numpy=
array([[10.,  7.],
       [ 3.,  2.],
       [ 8.,  9.]], dtype=float16)>

In [9]:
another_matrix.ndim

2

In [10]:
# Create a tensor
tensor = tf.constant([[[1, 2, 3],
                       [4, 5, 6]],
                      
                      [[7, 8, 9],
                       [10, 11, 12]],
                      
                      [[13, 14, 15],
                       [16, 17, 18]]])
tensor

<tf.Tensor: shape=(3, 2, 3), dtype=int32, numpy=
array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18]]], dtype=int32)>

In [11]:
tensor.ndim

3

## Create tensors with tf.variable

In [12]:
changeable_tensor = tf.Variable([10, 7])
unchangeable_tensor = tf.constant([10, 7])
changeable_tensor, unchangeable_tensor

(<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10,  7], dtype=int32)>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([10,  7], dtype=int32)>)

In [13]:
changeable_tensor[0].assign(7)

<tf.Variable 'UnreadVariable' shape=(2,) dtype=int32, numpy=array([7, 7], dtype=int32)>

In [14]:
# unchangeable_tensor[0].assign(7)
# will throw: AttributeError: 'tensorflow.python.framework.ops.EagerTensor' object has no attribute 'assign'

## Creating random tensors

In [15]:
random_1 = tf.random.Generator.from_seed(42) # Set seed for reproducibility
random_1 = random_1.normal(shape=(3,2))
random_2 = tf.random.Generator.from_seed(42)
random_2 = random_2.normal(shape=(3, 2))

# Are tensors equal?
random_1, random_2, random_1 == random_2

(<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193763, -1.8107855 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193763, -1.8107855 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=bool, numpy=
 array([[ True,  True],
        [ True,  True],
        [ True,  True]])>)

In [16]:
# Shuffle a tensor (valuable for when you want to shuffle your data so the inherent order doesn't affect learning
not_shuffled = tf.constant([[10, 7],
                            [3, 4],
                            [2, 5]])

# Shuffle tensor
# Neet to set global seed and operation seed to get deterministic outputs
tf.random.set_seed(7)
tf.random.shuffle(not_shuffled, seed=7)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 3,  4],
       [10,  7],
       [ 2,  5]], dtype=int32)>

In [17]:
random_3 = tf.random.Generator.from_seed(5)
random_3 = random_3.normal(shape=(4,3))
random_3

<tf.Tensor: shape=(4, 3), dtype=float32, numpy=
array([[ 1.0278524 ,  0.27974114, -0.01347923],
       [ 1.845181  ,  0.97061104, -1.0242516 ],
       [-0.6544423 , -0.29738766, -1.3240396 ],
       [ 0.28785667, -0.8757901 , -0.08857018]], dtype=float32)>

In [18]:
tf.random.shuffle(random_3, seed=5)

<tf.Tensor: shape=(4, 3), dtype=float32, numpy=
array([[ 1.845181  ,  0.97061104, -1.0242516 ],
       [ 1.0278524 ,  0.27974114, -0.01347923],
       [-0.6544423 , -0.29738766, -1.3240396 ],
       [ 0.28785667, -0.8757901 , -0.08857018]], dtype=float32)>

### Other ways to make tensors

In [19]:
# create a tensor of all ones
tf.ones([10, 7])

<tf.Tensor: shape=(10, 7), dtype=float32, numpy=
array([[1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.]], dtype=float32)>

In [20]:
tf.zeros(shape=(3,4))

<tf.Tensor: shape=(3, 4), dtype=float32, numpy=
array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]], dtype=float32)>

### Turn NumPy arrays into tensors

The difference between NumPy arrays and TensorFlow tensors is that tensors can be run on a GPU (much faster for numerical computing)

In [21]:
import numpy as np
numpy_A = np.arange(1, 25, dtype=np.int32) # create a Numppy array between 1 and 25
numpy_A

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24], dtype=int32)

In [22]:
A = tf.constant(numpy_A, shape=(2, 3, 4))
B = tf.constant(numpy_A)
C = tf.constant(numpy_A, shape=(4, 6))
A, B, C

(<tf.Tensor: shape=(2, 3, 4), dtype=int32, numpy=
 array([[[ 1,  2,  3,  4],
         [ 5,  6,  7,  8],
         [ 9, 10, 11, 12]],
 
        [[13, 14, 15, 16],
         [17, 18, 19, 20],
         [21, 22, 23, 24]]], dtype=int32)>,
 <tf.Tensor: shape=(24,), dtype=int32, numpy=
 array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
        18, 19, 20, 21, 22, 23, 24], dtype=int32)>,
 <tf.Tensor: shape=(4, 6), dtype=int32, numpy=
 array([[ 1,  2,  3,  4,  5,  6],
        [ 7,  8,  9, 10, 11, 12],
        [13, 14, 15, 16, 17, 18],
        [19, 20, 21, 22, 23, 24]], dtype=int32)>)

## Getting information from tensors

- Shape
- Rank
- Axis or dimension
- Size

In [23]:
# Create rank 4 tensor (4 dimensions)
rank_4_tensor = tf.zeros(shape=[2, 3, 4, 5])
rank_4_tensor

<tf.Tensor: shape=(2, 3, 4, 5), dtype=float32, numpy=
array([[[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]]], dtype=float32)>

In [24]:
rank_4_tensor[0]

<tf.Tensor: shape=(3, 4, 5), dtype=float32, numpy=
array([[[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]]], dtype=float32)>

In [25]:
rank_4_tensor.shape, rank_4_tensor.ndim, tf.size(rank_4_tensor)

(TensorShape([2, 3, 4, 5]), 4, <tf.Tensor: shape=(), dtype=int32, numpy=120>)

In [26]:
2 * 3 * 4 * 5

120

In [27]:
# Get various attributes of our tensor
print("Datatype of every element:", rank_4_tensor.dtype)
print("Number of dimensions (rank):", rank_4_tensor.ndim)
print("Shape of tensor:", rank_4_tensor.shape)
print("Elements along the 0 axis:", rank_4_tensor.shape[0])
print("Elements along the last axis:", rank_4_tensor.shape[-1])
print("Total number of elements in tensor:", tf.size(rank_4_tensor).numpy())

Datatype of every element: <dtype: 'float32'>
Number of dimensions (rank): 4
Shape of tensor: (2, 3, 4, 5)
Elements along the 0 axis: 2
Elements along the last axis: 5
Total number of elements in tensor: 120


## Indexing tensors
Tensors can be indexed just like Python lists

In [28]:
# Get the first 2 elements of each dimension
rank_4_tensor[:2, :2, :2, :2]

<tf.Tensor: shape=(2, 2, 2, 2), dtype=float32, numpy=
array([[[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]],


       [[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]]], dtype=float32)>

In [29]:
# Get the first element from each dimension from each index excpet for the final one 
rank_4_tensor[:1, :1, :1] # or rank_4_tensor[:1, :1, :1, :] 

<tf.Tensor: shape=(1, 1, 1, 5), dtype=float32, numpy=array([[[[0., 0., 0., 0., 0.]]]], dtype=float32)>

In [30]:
# Create rank two tensor (2 dimensions)
rank_2_tensor = tf.constant([[10, 7],
                             [3, 4]])
rank_2_tensor.shape, rank_2_tensor.ndim

(TensorShape([2, 2]), 2)

In [31]:
# Get the last item of each of row of our rank 2 tensor
rank_2_tensor[:, -1]

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([7, 4], dtype=int32)>

In [32]:
# Add in extra dimension to our rank 2 tensor
rank_3_tensor = rank_2_tensor[..., tf.newaxis]
rank_3_tensor

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[10],
        [ 7]],

       [[ 3],
        [ 4]]], dtype=int32)>

In [33]:
# Alternative to tf.newaxis
tf.expand_dims(rank_2_tensor, axis=-1) # -1 means expand the final axis

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[10],
        [ 7]],

       [[ 3],
        [ 4]]], dtype=int32)>

In [34]:
tf.expand_dims(rank_2_tensor, axis=0) # expand the 1-axis

<tf.Tensor: shape=(1, 2, 2), dtype=int32, numpy=
array([[[10,  7],
        [ 3,  4]]], dtype=int32)>

## Manipulating tensors

In [35]:
# Adding values to a tenor using addition operator
tensor = tf.constant([[10, 7],
                      [7, 10]])
tensor + 10 

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[20, 17],
       [17, 20]], dtype=int32)>

In [36]:
tensor * 10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[100,  70],
       [ 70, 100]], dtype=int32)>

In [37]:
tensor - 10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 0, -3],
       [-3,  0]], dtype=int32)>

In [38]:
tf.multiply(tensor, 10)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[100,  70],
       [ 70, 100]], dtype=int32)>

### Matrix multiplication

also reffered to as a dot product

In [39]:
print(tensor.numpy())
tf.matmul(tensor, tensor).numpy()

[[10  7]
 [ 7 10]]


array([[149, 140],
       [140, 149]], dtype=int32)

In [40]:
tensor_2 = tf.constant([[1,2,5],
                        [7,2,1],
                        [3,3,3]])

tensor_3 = tf.constant([[3,5],
                        [6,7],
                        [1,8]])

tf.matmul(tensor_2, tensor_3)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[20, 59],
       [34, 57],
       [30, 60]], dtype=int32)>

In [41]:
tensor_2 @ tensor_3

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[20, 59],
       [34, 57],
       [30, 60]], dtype=int32)>

The inner dimensions of the tensors must match

In [42]:
X = tf.constant([[1, 2],
                 [3, 4],
                 [5, 6]])
Y = tf.constant([[7, 8],
                 [9, 10],
                 [11, 12]])

In [43]:
# Currenlty matrix X and Y sizes are incompatible
tf.reshape(Y, shape=(2, 3))


<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[ 7,  8,  9],
       [10, 11, 12]], dtype=int32)>

In [44]:
X @ tf.reshape(Y, shape=(2,3))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 27,  30,  33],
       [ 61,  68,  75],
       [ 95, 106, 117]], dtype=int32)>

In [45]:
X.shape, tf.reshape(Y, shape=(2,3)).shape

(TensorShape([3, 2]), TensorShape([2, 3]))

In [46]:
tf.matmul(tf.reshape(X, shape=(2,3)), Y)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 58,  64],
       [139, 154]], dtype=int32)>

In [47]:
# Can do similar thing with transpose
X, tf.transpose(X)

(<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[1, 2],
        [3, 4],
        [5, 6]], dtype=int32)>,
 <tf.Tensor: shape=(2, 3), dtype=int32, numpy=
 array([[1, 3, 5],
        [2, 4, 6]], dtype=int32)>)

In [48]:
X, Y

(<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[1, 2],
        [3, 4],
        [5, 6]], dtype=int32)>,
 <tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[ 7,  8],
        [ 9, 10],
        [11, 12]], dtype=int32)>)

In [49]:
# Preform dot product on X and Y with transposing
tf.tensordot(tf.transpose(X), Y, axes=1)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 89,  98],
       [116, 128]], dtype=int32)>

### Changing data type of the tensor

In [50]:
B = tf.constant([1.7, 7.4])
B.dtype

tf.float32

In [51]:
C = tf.constant([7, 10])
C.dtype

tf.int32

In [52]:
B = tf.cast(B, dtype=tf.float16)
B

<tf.Tensor: shape=(2,), dtype=float16, numpy=array([1.7, 7.4], dtype=float16)>

In [53]:
C = tf.cast(C, dtype=tf.float32)
C

<tf.Tensor: shape=(2,), dtype=float32, numpy=array([ 7., 10.], dtype=float32)>

### Aggregating tensors
Aggregating tensors = condensing them from multiple values down to a smaller amount of values

In [54]:
# Get the absolute values
D = tf.constant([-7, -10])
tf.abs(D)

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([ 7, 10], dtype=int32)>

In [55]:
E = tf.constant([[13, 4, 8],
                 [3, 5, 9]])

print('min value:', tf.math.reduce_min(E))
print('max value:', tf.math.reduce_max(E))
print('mean:',      tf.math.reduce_mean(E))
print('sum:',       tf.math.reduce_sum(E))
print('variance:',  tf.math.reduce_variance(tf.cast(E, dtype=tf.float32)))
print('standard deviation', tf.math.reduce_std(tf.cast(E, dtype=tf.float32)))

min value: tf.Tensor(3, shape=(), dtype=int32)
max value: tf.Tensor(13, shape=(), dtype=int32)
mean: tf.Tensor(7, shape=(), dtype=int32)
sum: tf.Tensor(42, shape=(), dtype=int32)
variance: tf.Tensor(11.666667, shape=(), dtype=float32)
standard deviation tf.Tensor(3.4156504, shape=(), dtype=float32)


In [56]:
F = tf.constant(np.random.randint(0, 100, size=20))
print(F)
print('min value:', tf.math.reduce_min(F))
print('max value:', tf.math.reduce_max(F))
print('mean:',      tf.math.reduce_mean(F))
print('sum:',       tf.math.reduce_sum(F))

tf.Tensor([26 50 81 50 72 39 23 63 29 31 22 99 20 17 22 99 66 57 24 30], shape=(20,), dtype=int64)
min value: tf.Tensor(17, shape=(), dtype=int64)
max value: tf.Tensor(99, shape=(), dtype=int64)
mean: tf.Tensor(46, shape=(), dtype=int64)
sum: tf.Tensor(920, shape=(), dtype=int64)


In [57]:
# Find a positional maximium and minimum
# print('argmax:', tf.math.argmax(E))
# print('argmin:', tf.math.argmin(E))

tf.random.set_seed(42)
F = tf.random.uniform(shape=[20])
F

<tf.Tensor: shape=(20,), dtype=float32, numpy=
array([0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
       0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
       0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
       0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ],
      dtype=float32)>

In [58]:
# Find a positional maximum
tf.math.argmax(F)

<tf.Tensor: shape=(), dtype=int64, numpy=15>

In [59]:
# Get largest value using a position
F[tf.math.argmax(F)], tf.math.reduce_max(F)

(<tf.Tensor: shape=(), dtype=float32, numpy=0.8996835>,
 <tf.Tensor: shape=(), dtype=float32, numpy=0.8996835>)

In [60]:
# Find a positional minimum
tf.math.argmin(F)

<tf.Tensor: shape=(), dtype=int64, numpy=16>

In [61]:
# Find a minimum using the positional minimum index
F[tf.math.argmin(F)], tf.math.reduce_min(F)

(<tf.Tensor: shape=(), dtype=float32, numpy=0.009463668>,
 <tf.Tensor: shape=(), dtype=float32, numpy=0.009463668>)